### ISSUE TITLE
Targeting macOS via Catalyst is not working

### ISSUE THREAD

**Issue by madejm** [Azure-Samples/communication-services-ios-calling-hero#68]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
In target AzureCalling under _Deployment Info_ enable checkbox for `Mac` to target iOS application to run on Mac Catalyst

### Any log messages given by the failure
In `MSAL` preprocessor removes two flags when targeting Mac Catalyst:
>Undefined symbol: _MSID_BROKER_APP_BUNDLE_ID
>Undefined symbol: _MSID_BROKER_APP_BUNDLE_ID_DF

`AzureCommunicationCalling`  XCFramework is not compiled for arm64/x86_64 Mac Catalyst:
>No such module 'AzureCommunicationCalling'

### Expected/desired behavior
Application runs on Mac Catalyst

### OS and Version?
>macOS 10.15 (Catalina) and newer
>Xcode 13.0

### Versions
>AzureCommunicationCalling (1.1.0)
>AzureCommunicationCommon (1.0.1)
>AzureCore (1.0.0-beta.12)
>MSAL (1.1.13)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jorgegarchirota** [comment]
Hi @madejm, can you please create a new entry over the ["Share ideas portal" ](https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858) this will help us to track all the feature requests and the community with similar questions as you, thank in advance!!
