### ISSUE TITLE
Join Call Not working when connected with different token but same session id/ teams link in the single in App Session.

### ISSUE THREAD

**Issue by DeeptiDhumavat** [Azure-Samples/communication-services-ios-calling-hero#82]
we have been trying to join call using the ios sdk using Acs/Teams by token that is received from an endpoint. Seems like different token and same session ID / Teams Link does not seems to join the call if ios joins in after web is in the call. The state is Connecting and then Disconnected from the sdk but never gets into Connected State. But same token and same session id always works. Also in case ios joins first in the meeting before web this works. The delegates are not getting called for Remote Participant as well.

For couple of times it works in the same session of the app after that it does not get connected. This behaviour have been reported past couple of weeks earlier to that it was working fine I guess. Are there any changes to the server made or is it a know issue?
If you could provide your inputs on the same at the earliest.

**Comment by waynemo** [comment]
@DeeptiDhumavat, thanks for the feedback. To help troubleshoot, we would like to clarify how to reproduce the issue. Could you confirm these are the steps taken?

1. On a web browser, join a Group Call using the Web Calling SDK and a valid token.
2. On an iOS simulator/device that is running the sample app from this repo, join the same Group Call with a different valid token fetched from an endpoint.
3. Upon joining, the iOS Calling SDK tries to connect then disconnects.

**Comment by DeeptiDhumavat** [comment]
@waynemo yes correct try web first and then followed by iOS. In the same Session of the App multiple times you would be able to reproduce. It might get connected some times but then after that constantly connecting and then disconnects with call end reason code as 408 and subside as 0.

**Comment by AmyL219** [comment]
@DeeptiDhumavat , thanks for reporting the bug. We are tracking down the issue in our backend right now. 
Will update you when the issue is fixed.

**Comment by DeeptiDhumavat** [comment]
@AmyL219 Any update on the same?

**Comment by AmyL219** [comment]
@DeeptiDhumavat, yeah, we have locked down the issue and mitigate part of the issue in the backend. You should have a better experience regarding this issue right now. 
But we still need to wait a new release with the fix of  our dependency` AzureCommunicationCalling`  ( The ETA is mid May) . 
However, there are some workarounds you can take to avoid this issue:
- Usually, the first time you start a call with the token fetch url/token, this bug wouldn't show up
- After you quit the call, wait around 1 minute before rejoin the call with same token fetch url/token
- Reuse the CallAgent/CallClient in the app. Right now, when the call is ended, the CallAgent/CallClient would be killed. And recreate ones once user tap joinCall/StartCall. We probably will create PR to reuse  CallAgent/CallClient inside the Calling Hero App

**Comment by AmyL219** [comment]
@DeeptiDhumavat, we have fixed this issue in the latest commit!
